[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ETSAP - TIMES Reference"
authors = [{name = "ESMIA", email = "info@esmia.ca"}]
dynamic = ["version", "description"]
